name: Build and Test

on:
  push:
    branches: [ actions ]
  pull_request:
    branches: [ actions ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: mkdir
      run: mkdir -p bin/
    - name: make
      run: make ALL_NEW
    - name: test
      run: make test

